# Generated by Django 4.2.6 on 2023-10-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='media/profile_pic')),
                ('mobilenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('identitytype', models.CharField(max_length=200)),
                ('identitycardnumber', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('destinations', models.CharField(max_length=250)),
                ('fromdate', models.CharField(max_length=250)),
                ('todate', models.CharField(max_length=250)),
                ('cost', models.IntegerField(default=0)),
                ('passcreated_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
            ],
        ),
    ]
