# Generated by Django 4.2.6 on 2023-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='profile_pic1',
        ),
    ]
