# Generated by Django 4.2.6 on 2023-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_profile_pic_customuser_profile_pic1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobilenumber',
            field=models.IntegerField(default=0),
        ),
    ]
