# Generated by Django 4.2.6 on 2024-02-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobilenumber',
        ),
    ]
