# Generated by Django 4.2.6 on 2024-02-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customuser_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic1',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='passes',
            name='profile_pic',
            field=models.ImageField(upload_to='media/userprofile_pic'),
        ),
    ]
