# Generated by Django 4.2.6 on 2024-02-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_profile_pic1_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passes',
            old_name='profile_pic',
            new_name='profile_pic1',
        ),
    ]
