# Generated by Django 4.2.6 on 2024-02-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_profile_pic_passes_profile_pic1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='profile_pic1',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
